package in.co.rays.proj3.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import in.co.rays.proj3.dto.BaseDTO;
import in.co.rays.proj3.dto.ReportDTO;
import in.co.rays.proj3.dto.UserDTO;
import in.co.rays.proj3.exception.ApplicationException;
import in.co.rays.proj3.exception.DatabaseException;
import in.co.rays.proj3.exception.DuplicateRecordException;
import in.co.rays.proj3.model.ModelFactory;
import in.co.rays.proj3.model.ReportModelInt;
import in.co.rays.proj3.model.UserModelInt;
import in.co.rays.proj3.util.DataUtility;
import in.co.rays.proj3.util.DataValidator;
import in.co.rays.proj3.util.PropertyReader;
import in.co.rays.proj3.util.ServletUtility;

@WebServlet(name="ReportCtl",urlPatterns={"/ctl/ReportCtl"})
public class ReportCtl extends BaseCtl {
	
	@Override
	protected boolean validate(HttpServletRequest request) {
		
		boolean pass=true;
		
		if(DataValidator.isNull(request.getParameter("reportName"))) {
			request.setAttribute("reportName", PropertyReader.getValue("error.require","Report Name"));
			pass=false;
		}else if(!DataValidator.isName(request.getParameter("reportName"))) {
			request.setAttribute("reportName", "Invalid Report Name");
			pass=false;
		}
		
		if(DataValidator.isNull(request.getParameter("generatedBy"))) {
			request.setAttribute("generatedBy", PropertyReader.getValue("error.require","Generated By"));
			pass=false;
		}
		
		if(DataValidator.isNull(request.getParameter("reportStatus"))) {
			request.setAttribute("reportStatus", PropertyReader.getValue("error.require","Report Status"));
			pass=false;
		}
		
		if(DataValidator.isNull(request.getParameter("generatedDate"))) {
			request.setAttribute("generatedDate", PropertyReader.getValue("error.require","Generated Date"));
			pass=false;
		}else if(!DataValidator.isDate(request.getParameter("generatedDate"))) {
			request.setAttribute("generatedDate", "Invalid Generated Date");
			pass=false;
		}	
		
		return pass;
	}
	
	@Override
	protected BaseDTO populateDTO(HttpServletRequest request) {
		
		ReportDTO dto=new ReportDTO();
		
		dto.setId(DataUtility.getLong(request.getParameter("id")));
		dto.setReportName(DataUtility.getString(request.getParameter("reportName")));
		dto.setGeneratedDate(DataUtility.getDate(request.getParameter("generatedDate")));
		System.out.println("REport Generated Date in ReportCtl:"+dto.getGeneratedDate());
		dto.setGeneratedBy(DataUtility.getString(request.getParameter("generatedBy")));
		dto.setReportStatus(DataUtility.getString(request.getParameter("reportStatus")));
		
		populateBean(dto, request);
		
		return dto;
	}
	
	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException,DatabaseException {
	
		long id = DataUtility.getLong(request.getParameter("id"));

		ReportModelInt model=ModelFactory.getInstance().getReportModel();

		if (id > 0) {
			try {
				ReportDTO dto=model.findByPK(id);
				ServletUtility.setDto(dto, request);
				//ServletUtility.setBean(bean, request);
			} catch (ApplicationException e) {
				e.printStackTrace();
				ServletUtility.handleException(e, request, response);
				return;
			}
		}
		ServletUtility.forward(getView(), request, response);
	}
	
	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException,DatabaseException {
		String op=DataUtility.getString(request.getParameter("operation"));
		ReportModelInt model=ModelFactory.getInstance().getReportModel();
		long id=DataUtility.getLong(request.getParameter("id"));
		
		if(OP_SAVE.equalsIgnoreCase(op)) {
			ReportDTO dto=(ReportDTO)populateDTO(request);
			try {
				if(id>0) {
					model.update(dto);
					ServletUtility.setSuccessMessage("Data is successfully updated", request);
				}else {
					model.add(dto);
					ServletUtility.setSuccessMessage("Data is successfully added",request);
				}
				ServletUtility.setDto(dto, request);
			} catch (DuplicateRecordException e) {
				e.printStackTrace();
				ServletUtility.handleException(e, request, response, "Report", dto);
			}catch(ApplicationException e) {
				e.printStackTrace();
				ServletUtility.handleException(e, request, response);
				return;
			}
		}else if((OP_RESET.equalsIgnoreCase(op))) {
			ServletUtility.forward(getView(), request, response);
			return;
		}
		
		ServletUtility.forward(getView(), request, response);
	}
	
	@Override
	protected String getView() {
		return ORSView.REPORT_VIEW;
	}

}
