<%@page import="in.co.rays.proj3.controller.ORSView"%>
<%@page import="in.co.rays.proj3.controller.ReportCtl"%>
<%@page import="in.co.rays.proj3.dto.ReportDTO"%>
<%@page import="java.util.List"%>
<%@page import="java.util.HashMap"%>
<%@page import="in.co.rays.proj3.util.HTMLUtility"%>
<%@page import="in.co.rays.proj3.util.DataUtility"%>
<%@page import="in.co.rays.proj3.util.ServletUtility"%>

<html>
<head>
<meta charset="ISO-8859-1">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Add Report</title>
<link rel="icon" type="image/png" href="<%=ORSView.APP_CONTEXT%>/img/logo.png" sizes="16x16" />
<script type="text/javascript" src="/Project-03/js/datepicker.js"></script>

<style>
	.bgColor {
            background-color: white;
            padding-top: 120px;
            /* Because header is fixed */
            padding-bottom: 80px;
            /* Because footer is fixed */
        }

        .input-group-addon {
            box-shadow: 9px 8px 7px #001a33;
        }
	h1,h2,h3{
		color:#004e92;
	}

</style>
<link rel="stylesheet"
href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>

<script type="text/javascript" src="/Project-03/js/datepicker.js"></script>

<script>
var currentYear = new Date().getFullYear();
var maxYear = currentYear - 18;
    $(function() {
        $("#udate").datepicker({
        	dateFormat : 'dd-mm-yy',
    		changeMonth : true,
    		changeYear : true,
    		yearRange : '1970:' + maxYear,
    		minDate : new Date(1970, 0, 1),
    		maxDate : new Date(maxYear, 11, 31)
        });
    });
</script>

</head>
<body class="bgColor">

<!-- Header -->
	<%@ include file="Header.jsp" %>
	
<!-- Bean Tag -->
	<jsp:useBean id="dto" class="in.co.rays.proj3.dto.ReportDTO" scope="request"></jsp:useBean>
	
	
<!-- Main Content -->
	<div class="container pt-4">
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6">
				<div class="card input-group-addon">
					<div class="card-body">
						<%
							long id = DataUtility.getLong(request.getParameter("id"));
						
							if(dto.getId()!=null && dto.getId()>0){						
						%>				
						<h3 class="text-center text-primary pb-3">Update Report</h3>
						<%}else { %>
						<h3 class="text-center text-primary pb-3">Add Report</h3>
						<%} %>
						
						<!-- Static Success Message -->
 						<%if(ServletUtility.getSuccessMessage(request).length()>0){ %>
 						<div class="alert alert-success alert-dismissable">
 						<button type="button" class="close" data-dismiss="alert">&times;</button>
                            <h4><%=ServletUtility.getSuccessMessage(request)%></h4>
 						</div>
 						<%} %>
 						
 						
 						<!-- Static Error Message -->
 						<%if(ServletUtility.getErrorMessage(request).length()>0) {%>
 						<div class="alert alert-danger alert-dismissable">
 						<button type="button" class="close" data-dismiss="alert">&times;</button>
                            <h4><%=ServletUtility.getErrorMessage(request)%></h4>
 						</div>
 						<% }%>
						
						
						<!-- Form Start -->
						<form action="<%=ORSView.REPORT_CTL %>" method="post">
						
						
						
						<!-- Report Name-->
 							<label><b>Report Name</b><span style="color:red">*</span></label>
 							<div class="input-group mb-3">
 								<div class="input-class-prepend">
 									<span class="input-group-text" id="basic-addon1"><i class="fa fa-clock" style="font-size: 25px;"></i></span>
 									
 								</div>
 								
 								<input type="text" class="form-control" name="reportName" placeholder="Report Name" 
 								value="<%=DataUtility.getStringData(dto.getReportName())%>">
 								</div>
 								<font color="red"><%=ServletUtility.getErrorMessage("reportName", request)%></font><br>
 								
 						
 						<!-- Report Generated Date-->
 							<label><b>Report Generated Date</b><span style="color: red">*</span></label>
							<div class="input-group mb-3">
								<div class="input-class-prepend">
									<span class="input-group-text" id="basic-addon1"><i
										class="fas fa-calendar-alt" style="font-size: 25px;"></i></span>

								</div>
								<input type="text" id="udate" name="generatedDate"
									placeholder="Select Generated Date"
									value="<%=DataUtility.getDateString(dto.getGeneratedDate())%>">
									</div>
								<font color="red"><%=ServletUtility.getErrorMessage("generatedDate", request)%></font><br>	
						
						<!-- Report Generated By-->
 							<label><b>Report Generated By</b><span style="color:red">*</span></label>
 							<div class="input-group mb-3">
 								<div class="input-group-prepend">
 									<span class="input-group-text" id="basic-addon1"><i class="fa fa-clock" style="font-size: 25px;"></i></span>
 									
 								</div>
 								
 								<input type="text" class="form-control" name="generatedBy" placeholder="Report Generated By" 
 								value="<%=DataUtility.getStringData(dto.getGeneratedBy())%>">
 								</div>
 								<font color="red"><%=ServletUtility.getErrorMessage("generatedBy", request)%></font><br>
 								
							<!--Report Status -->
 							<label><b>Report Status</b><span style="color:red">*</span></label>
 							<div class="input-group mb-3">
 								<div class="input-group-prepend">
 									<span class="input-group-text" id="basic-addon1"><i class="fa fa-list" style="font-size: 25px;"></i></span>
 									
 								</div>
 								<input type="text" class="form-control" name="reportStatus" placeholder="Report Status"
 								value="<%=DataUtility.getStringData(dto.getReportStatus())%>">
 								</div>
 								<font color="red"><%=ServletUtility.getErrorMessage("reportStatus", request)%></font><br> 
 												
								
 							
							<input type="hidden" name="id" value="<%=dto.getId()%>">
            				<input type="hidden" name="createdBy" value="<%=dto.getCreatedBy()%>">
            				<input type="hidden" name="modifiedBy" value="<%=dto.getModifiedBy()%>">
            				<input type="hidden" name="createdDatetime" value="<%=DataUtility.getTimestamp(dto.getCreatedDatetime())%>">
           					 <input type="hidden" name="modifiedDatetime" value="<%=DataUtility.getTimestamp(dto.getModifiedDatetime())%>">					
						
						<!-- Buttons -->
						<div class="text-center">
							<input type="submit" class="btn btn-success" name="operation" value="<%=ReportCtl.OP_SAVE%>" >						
						
						<%
                        if (dto.getId() !=null) {
                    %>
                                                
                                
                                <input type="submit" class="btn btn-secondary" name="operation"value="<%=ReportCtl.OP_CANCEL%>"><br>  								                          
                            </div> 							
						
                    <%
                        } else {
                    %>
                                                
                                
                                <input type="submit" class="btn btn-secondary" name="operation"value="<%=ReportCtl.OP_RESET%>"><br>  								                          
                            </div> 							
						
                    <%
                        }
                    %>						
						</form>							
					</div>
				</div>
				
			</div>
			<div class="col-md-3"></div>	
		</div>
	
	</div>
	
	
	<!-- Footer -->
	<%@ include file="Footer.jsp"%>
</body>
</html>